name: autocomplete_textfield
description: A simple and versatile autocomplete text field for flutter that supports custom datatypes.
version: 3.0.0
author: Felix McCuaig <felixmccuaigdev@gmail.com>
homepage: https://github.com/felixlucien/flutter-autocomplete-textfield

environment:
    sdk: ">=2.12.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
